bills:
  airtel:
    typ: airtel_postpaid
    keep_pages: 4
    label:
    password: password

  jio:
    typ: jio_postpaid
    keep_pages: 5
    label:
    password: password

  jiofiber:
    typ: jio_fiber
    keep_pages: 5
    label:
    password: password

download_dir: /Users/arunvelsriram/Downloads/sodexwoe
