bills:
  personal:
    typ: airtel_postpaid
    keep_pages: 4
    label: Postpaid Bills/Airtel
    password: password

  work:
    typ: jio_postpaid
    keep_pages: 5
    label: Postpaid Bills/Jio
    password: password
    additional_text: "GST Number: ABC123"

download_dir: ~/Downloads/sodexwoe
